language: node_js
sudo: false
node_js:
- '4.1.1'

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - grunt build
