language: node_js
sudo: false

# cache:
#   directories:
#     - node_modules
#     - bower_components

install:
  - npm uninstall -g phantomjs
  - npm install -g phantomjs2
  - npm install -g bower

script:
  - grunt build
